# Generated by Django 4.2.1 on 2023-05-10 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('post', models.TextField()),
                ('autor', models.CharField(max_length=50)),
                ('thumb', models.ImageField(upload_to='thumb_cursos')),
                ('thumbUrl', models.URLField(blank=True, max_length=256, null=True)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('comentarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comentarios')),
            ],
        ),
    ]
