# Generated by Django 4.2.1 on 2023-05-10 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.posts'),
            preserve_default=False,
        ),
    ]
