# Generated by Django 4.1.2 on 2023-06-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_popup',
            field=models.URLField(blank=True, null=True),
        ),
    ]
