# Generated by Django 4.1.2 on 2023-06-09 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='audio',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
