# Generated by Django 4.2.1 on 2023-06-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_sobremim_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigoacademiaco',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materias',
            name='image',
            field=models.ImageField(default=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
