# Generated by Django 4.2.1 on 2023-06-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_artigoacademiaco_image_materias_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='link',
            new_name='Lattes',
        ),
        migrations.AddField(
            model_name='contato',
            name='academia_edu',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='orcid',
            field=models.URLField(blank=True, null=True),
        ),
    ]
