# Generated by Django 4.2.1 on 2023-06-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_link_contato_lattes_contato_academia_edu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigoacademiaco',
            name='descricao',
            field=models.TextField(max_length=141),
        ),
        migrations.AlterField(
            model_name='materias',
            name='descricao',
            field=models.TextField(max_length=141),
        ),
    ]
