# Generated by Django 4.1.2 on 2023-06-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_artigoacademiaco_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='descricao',
            field=models.TextField(max_length=50),
        ),
    ]
