# Generated by Django 4.1.2 on 2023-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_materias_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigoacademiaco',
            name='descricao',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
